export const ADD_POSITION = 'ADD_POSITION';
export const REMOVE_POSITION = 'REMOVE_POSITION';
export const INIT_POSITIONS = 'INIT_POSITIONS';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILURE = 'ORDER_FAILURE';

export const POSITION_REQUEST = 'POSITION_REQUEST';
export const POSITION_SUCCESS = 'POSITION_SUCCESS';
export const POSITION_FAILURE = 'POSITION_FAILURE';